export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_REQUEST";

export const REGISTER_USER_REQUEST = "REGiSTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_REQUEST";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_REQUEST";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USERS_DETAILS_REQUEST = "USERS_DETAILS_REQUEST";
export const USERS_DETAILS_SUCCESS = "USERS_DETAILS_SUCCESS";
export const USERS_DETAILS_FAIL = "USERS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
